# Generated by Django 5.2.7 on 2025-11-04 11:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TelemetryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=50)),
                ('circuit_name', models.CharField(max_length=100)),
                ('lap', models.IntegerField(default=0)),
                ('speed', models.FloatField()),
                ('throttle', models.FloatField()),
                ('brake', models.FloatField()),
                ('gear', models.IntegerField(default=0)),
                ('rpm', models.IntegerField(default=0)),
                ('drs', models.BooleanField(default=False)),
                ('time', models.DateTimeField(auto_now=True)),
                ('session_type', models.CharField(max_length=100)),
            ],
            options={
                'indexes': [models.Index(fields=['driver_name'], name='ingestion_t_driver__b9c1d0_idx'), models.Index(fields=['team'], name='ingestion_t_team_4449ff_idx'), models.Index(fields=['circuit_name'], name='ingestion_t_circuit_ea0e1c_idx')],
            },
        ),
    ]
