# Generated by Django 5.2.7 on 2025-11-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0002_eventlog_telemetry_telemetrydata_session_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telemetrydata',
            name='tyre',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='telemetrydata',
            name='weather',
            field=models.BooleanField(default=False),
        ),
    ]
