# Generated by Django 5.2.7 on 2025-11-14 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0003_telemetrydata_tyre_telemetrydata_weather'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telemetrydata',
            name='weather',
            field=models.FloatField(default=0),
        ),
    ]
