# Generated by Django 5.2.7 on 2025-11-14 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0003_telemetrydata_tyre_telemetrydata_weather'),
    ]

    operations = [
        migrations.CreateModel(
            name='analytics_and_prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('ai_response', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('telemetry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ingestion.telemetrydata')),
            ],
        ),
    ]
